#!/usr/bin/env bash
# Refreshes the self-hosted copies of Nunito and Russo One.
#
# The game ships the faces rather than linking Google's CDN: a game running
# inside somebody else's iframe should not depend on a third-party host that
# can be slow or unreachable, because when it is, every heading and button
# falls back to a system face and the game reads as broken rather than
# styled. Both families are SIL Open Font License, so shipping them is
# allowed.
set -euo pipefail
cd "$(dirname "$0")/.."

URL='https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800;900&family=Russo+One&display=swap'
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
OUT='public/assets/fonts'

mkdir -p "$OUT"
curl -sS -A "$UA" "$URL" -o "$OUT/.remote.css"

python3 - "$OUT" <<'PY'
import hashlib, re, subprocess, sys
from pathlib import Path
out = Path(sys.argv[1])
css = (out / '.remote.css').read_text()
for url in sorted(set(re.findall(r'https://fonts\.gstatic\.com[^)]+', css))):
    name = (re.search(r'/s/([a-z]+)/', url) or [None, 'font'])[1]
    filename = f'{name}-{hashlib.sha1(url.encode()).hexdigest()[:8]}.woff2'
    subprocess.run(['curl', '-sS', '-o', str(out / filename), url], check=True)
    # Relative to this stylesheet, which already lives in assets/fonts —
    # a path from the site root would resolve to assets/fonts/assets/fonts.
    css = css.replace(url, f'./{filename}')
(out / 'fonts.css').write_text(
    '/* Generated by tool/fetch-fonts.sh — do not edit by hand. */\n' + css)
PY

rm -f "$OUT/.remote.css"
echo "шрифтов: $(ls "$OUT"/*.woff2 | wc -l | tr -d ' '), суммарно $(du -sh "$OUT" | cut -f1)"
